### ISSUE TITLE
As a client, I would like to see a locally hosted, concept HTML page so that I am able to request changes as needed.

### ISSUE THREAD

**Issue by djjeong127** [filo-movie/filomovie#21]
**Acceptance Tests**

*Test 1*
1. Open the root HTML page locally
2. Verify that typing in the search bar and clicking on the search button works.
3. Verify that mock movie posters show up when searched
4. Click on a mock movie poster
5. Verify that the movie poster and streaming services show up

**Comment by ngc1514** [comment]
![21](https://user-images.githubusercontent.com/30205154/134961656-a331b766-65ec-4ecd-a877-3c954f4fc383.png)
