### ISSUE TITLE
As a developer, I would like to make my website dynamic with the data from the backend so that when I search a movie, the correct data is displayed

### ISSUE THREAD

**Issue by AMdaiyan** [filo-movie/filomovie#52]
**Acceptance Tests**

*Test 1*
1. Open FiloMovie website
2. Search "8 Mile" into the search bar
3. 8 Mile's Title name and movie poster should appear

**Comment by ngc1514** [comment]
![image](https://user-images.githubusercontent.com/30205154/140597589-3bd25c94-3347-4f05-884a-f91192e919e5.png)
![image](https://user-images.githubusercontent.com/30205154/140597593-ce231ce2-ec33-4f46-8172-cb000549e158.png)
