### ISSUE TITLE
As a movie watcher, I'd like to click on a movie poster and see the relevant information for it so I can read about it

### ISSUE THREAD

**Issue by djjeong127** [filo-movie/filomovie#55]
**Acceptance Tests**

*Test 1*
1. go to https://filomovie.herokuapp.com/
2.  search "8 Mile"
3. click the movie poster for 8 Mile
5.  Should look like this
![image.png](https://images.zenhubusercontent.com/61366a18784bf2f1bda0fa11/b40b9231-37fa-493b-9836-2efcf03fc0e7)

**Comment by alejandrorizquierdo** [comment]
https://images.zenhubusercontent.com/403734864/c233cb93-9ec9-4299-b21c-9330e7efdd9e/8_mile.mov
