### ISSUE TITLE
As a movie watcher, I'd like to click on an available streaming service and see the google search results for that streaming service to see where I can see the movie

### ISSUE THREAD

**Issue by djjeong127** [filo-movie/filomovie#80]
*Acceptance Tests*

*Test 1*
1. go to https://filomovie.herokuapp.com/
2. search "Forrest Gump"
3. click on "Forrest Gump" poster
4. click on "Spectrum on Demand"
5. see the google search for Spectrum on Demand

**Comment by ngc1514** [comment]
![image](https://user-images.githubusercontent.com/30205154/144544188-1a9eb3fd-ddb9-4633-99cd-8130b3ff4cee.png)
![image](https://user-images.githubusercontent.com/30205154/144544191-e6a945e7-b90d-432a-98de-b75e0a41e280.png)
