### ISSUE TITLE
As a movie watcher, I'd like to see the rating, genre, movie runtime, and release date for a movie for more in depth information about it

### ISSUE THREAD

**Issue by djjeong127** [filo-movie/filomovie#81]
**Acceptance Tests**

*Test 1*
1. go to https://filomovie.herokuapp.com/
2. search "8 Mile"
3. click on "8 Mile" poster
4. see rating, genre, movie runtime and release date on page

**Comment by ngc1514** [comment]
![image](https://user-images.githubusercontent.com/30205154/144544061-90d4bbb6-50ee-4de7-bac5-3c1a0912ddbb.png)
